{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.6.13"
    },
    "colab": {
      "name": "intro.ipynb",
      "provenance": []
    },
    "accelerator": "GPU",
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "1a32beb3196b435e81d9233cf04d95d7": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HBoxView",
            "_dom_classes": [],
            "_model_name": "HBoxModel",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "box_style": "",
            "layout": "IPY_MODEL_49e91668342a4cc396700badbdbd9417",
            "_model_module": "@jupyter-widgets/controls",
            "children": [
              "IPY_MODEL_9e9d9fae4def41898a36928c2d34381b",
              "IPY_MODEL_3213d9d5503b422db7fa87a2296c11d3",
              "IPY_MODEL_918183dfdd8141049eb969d9daf75942"
            ]
          }
        },
        "49e91668342a4cc396700badbdbd9417": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "9e9d9fae4def41898a36928c2d34381b": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_a767da434c7642d8bb83e678183c5228",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": "",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_03bd9583ecd84f889e34f16f19fb8236"
          }
        },
        "3213d9d5503b422db7fa87a2296c11d3": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "ProgressView",
            "style": "IPY_MODEL_92395284a05043e8afa42ad73ecf21e5",
            "_dom_classes": [],
            "description": "",
            "_model_name": "FloatProgressModel",
            "bar_style": "success",
            "max": 9912422,
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": 9912422,
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "orientation": "horizontal",
            "min": 0,
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_a17a9d2e20d5487c8eb9b360335353fd"
          }
        },
        "918183dfdd8141049eb969d9daf75942": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_7f7bf9ea3f0246218f7ba6728ff25d96",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": " 9913344/? [00:00&lt;00:00, 52258131.56it/s]",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_5143ea6ad2d144278cad0cbe285d7a37"
          }
        },
        "a767da434c7642d8bb83e678183c5228": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "03bd9583ecd84f889e34f16f19fb8236": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "92395284a05043e8afa42ad73ecf21e5": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "ProgressStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "bar_color": null,
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "a17a9d2e20d5487c8eb9b360335353fd": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "7f7bf9ea3f0246218f7ba6728ff25d96": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "5143ea6ad2d144278cad0cbe285d7a37": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "6a27f422bcb34d9088444cb8c0ae72e0": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HBoxView",
            "_dom_classes": [],
            "_model_name": "HBoxModel",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "box_style": "",
            "layout": "IPY_MODEL_34a990a09a994f059ab2b00890a243db",
            "_model_module": "@jupyter-widgets/controls",
            "children": [
              "IPY_MODEL_72717cd637264beb87bc38caffbce112",
              "IPY_MODEL_8a454e08f9e24605b511cca3202e9bda",
              "IPY_MODEL_dca5adf80ef548669c2c427de59d813f"
            ]
          }
        },
        "34a990a09a994f059ab2b00890a243db": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "72717cd637264beb87bc38caffbce112": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_311b56bee70b4742b0a4798a844c7ae8",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": "",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_e890a6e6fce14af994570a8d90ef830e"
          }
        },
        "8a454e08f9e24605b511cca3202e9bda": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "ProgressView",
            "style": "IPY_MODEL_fddd4bef12ed429f932af3a270af37c8",
            "_dom_classes": [],
            "description": "",
            "_model_name": "FloatProgressModel",
            "bar_style": "success",
            "max": 28881,
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": 28881,
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "orientation": "horizontal",
            "min": 0,
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_06796b0231564291a0194c16f54b6649"
          }
        },
        "dca5adf80ef548669c2c427de59d813f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_c5e4918837fe4363b2c56c0ffb8d3bfc",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": " 29696/? [00:00&lt;00:00, 717258.28it/s]",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_4656b891700e4e19be10cbbde829d8a4"
          }
        },
        "311b56bee70b4742b0a4798a844c7ae8": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "e890a6e6fce14af994570a8d90ef830e": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "fddd4bef12ed429f932af3a270af37c8": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "ProgressStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "bar_color": null,
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "06796b0231564291a0194c16f54b6649": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "c5e4918837fe4363b2c56c0ffb8d3bfc": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "4656b891700e4e19be10cbbde829d8a4": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "59036c1bfadd44ac90993bc44aeeb048": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HBoxView",
            "_dom_classes": [],
            "_model_name": "HBoxModel",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "box_style": "",
            "layout": "IPY_MODEL_cd1480e1a5a14a37be7534cc095e9357",
            "_model_module": "@jupyter-widgets/controls",
            "children": [
              "IPY_MODEL_ff2c73258fc0439da26d91c3fd997a28",
              "IPY_MODEL_765566c819214ff4ae7e9bfd2460a21b",
              "IPY_MODEL_b39a9f7796144a078c32511e42329e45"
            ]
          }
        },
        "cd1480e1a5a14a37be7534cc095e9357": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "ff2c73258fc0439da26d91c3fd997a28": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_1411506fa0764e51852898270ca60454",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": "",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_421b7a87bcf74f5384edbe0918161c10"
          }
        },
        "765566c819214ff4ae7e9bfd2460a21b": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "ProgressView",
            "style": "IPY_MODEL_961bb99ee0a84265bb0ce6d43a6a5d2a",
            "_dom_classes": [],
            "description": "",
            "_model_name": "FloatProgressModel",
            "bar_style": "success",
            "max": 1648877,
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": 1648877,
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "orientation": "horizontal",
            "min": 0,
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_86f524ee3cdd4bb59c9c30ac6ef92135"
          }
        },
        "b39a9f7796144a078c32511e42329e45": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_55d7e6b72dc040db8d290cd6bf338912",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": " 1649664/? [00:00&lt;00:00, 17575140.75it/s]",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_b5226d91bab64f5d81495118c48c2f33"
          }
        },
        "1411506fa0764e51852898270ca60454": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "421b7a87bcf74f5384edbe0918161c10": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "961bb99ee0a84265bb0ce6d43a6a5d2a": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "ProgressStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "bar_color": null,
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "86f524ee3cdd4bb59c9c30ac6ef92135": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "55d7e6b72dc040db8d290cd6bf338912": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "b5226d91bab64f5d81495118c48c2f33": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "b4b2de9a20f1416ea2391ffc98b00572": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HBoxView",
            "_dom_classes": [],
            "_model_name": "HBoxModel",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "box_style": "",
            "layout": "IPY_MODEL_e6906d8bc7b442e5bd133fb5dfcf3a51",
            "_model_module": "@jupyter-widgets/controls",
            "children": [
              "IPY_MODEL_dab39c446e844a0d83573f94723e0eeb",
              "IPY_MODEL_56ed682cb9e7475bbec1439ff4b09517",
              "IPY_MODEL_6bbcf32781424f24845117f676b53822"
            ]
          }
        },
        "e6906d8bc7b442e5bd133fb5dfcf3a51": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "dab39c446e844a0d83573f94723e0eeb": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_7cbedad663d5496a86c0b7addf5ba6b5",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": "",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_20d304c936d242e6abae011f5d6ae1c6"
          }
        },
        "56ed682cb9e7475bbec1439ff4b09517": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "ProgressView",
            "style": "IPY_MODEL_0e4e1e85049949f395759943b4f880de",
            "_dom_classes": [],
            "description": "",
            "_model_name": "FloatProgressModel",
            "bar_style": "success",
            "max": 4542,
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": 4542,
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "orientation": "horizontal",
            "min": 0,
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_70748f7bbe284433af3bf0b86b6bf4f9"
          }
        },
        "6bbcf32781424f24845117f676b53822": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "HTMLView",
            "style": "IPY_MODEL_e96c11a8c4ae44aa8beec893d2ade0f2",
            "_dom_classes": [],
            "description": "",
            "_model_name": "HTMLModel",
            "placeholder": "​",
            "_view_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "value": " 5120/? [00:00&lt;00:00, 63859.04it/s]",
            "_view_count": null,
            "_view_module_version": "1.5.0",
            "description_tooltip": null,
            "_model_module": "@jupyter-widgets/controls",
            "layout": "IPY_MODEL_f801a2f340f24e84b7f427956c83bc53"
          }
        },
        "7cbedad663d5496a86c0b7addf5ba6b5": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "20d304c936d242e6abae011f5d6ae1c6": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "0e4e1e85049949f395759943b4f880de": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "ProgressStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "bar_color": null,
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "70748f7bbe284433af3bf0b86b6bf4f9": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        },
        "e96c11a8c4ae44aa8beec893d2ade0f2": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_view_name": "StyleView",
            "_model_name": "DescriptionStyleModel",
            "description_width": "",
            "_view_module": "@jupyter-widgets/base",
            "_model_module_version": "1.5.0",
            "_view_count": null,
            "_view_module_version": "1.2.0",
            "_model_module": "@jupyter-widgets/controls"
          }
        },
        "f801a2f340f24e84b7f427956c83bc53": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_view_name": "LayoutView",
            "grid_template_rows": null,
            "right": null,
            "justify_content": null,
            "_view_module": "@jupyter-widgets/base",
            "overflow": null,
            "_model_module_version": "1.2.0",
            "_view_count": null,
            "flex_flow": null,
            "width": null,
            "min_width": null,
            "border": null,
            "align_items": null,
            "bottom": null,
            "_model_module": "@jupyter-widgets/base",
            "top": null,
            "grid_column": null,
            "overflow_y": null,
            "overflow_x": null,
            "grid_auto_flow": null,
            "grid_area": null,
            "grid_template_columns": null,
            "flex": null,
            "_model_name": "LayoutModel",
            "justify_items": null,
            "grid_row": null,
            "max_height": null,
            "align_content": null,
            "visibility": null,
            "align_self": null,
            "height": null,
            "min_height": null,
            "padding": null,
            "grid_auto_rows": null,
            "grid_gap": null,
            "max_width": null,
            "order": null,
            "_view_module_version": "1.2.0",
            "grid_template_areas": null,
            "object_position": null,
            "object_fit": null,
            "grid_auto_columns": null,
            "margin": null,
            "display": null,
            "left": null
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 756,
          "referenced_widgets": [
            "1a32beb3196b435e81d9233cf04d95d7",
            "49e91668342a4cc396700badbdbd9417",
            "9e9d9fae4def41898a36928c2d34381b",
            "3213d9d5503b422db7fa87a2296c11d3",
            "918183dfdd8141049eb969d9daf75942",
            "a767da434c7642d8bb83e678183c5228",
            "03bd9583ecd84f889e34f16f19fb8236",
            "92395284a05043e8afa42ad73ecf21e5",
            "a17a9d2e20d5487c8eb9b360335353fd",
            "7f7bf9ea3f0246218f7ba6728ff25d96",
            "5143ea6ad2d144278cad0cbe285d7a37",
            "6a27f422bcb34d9088444cb8c0ae72e0",
            "34a990a09a994f059ab2b00890a243db",
            "72717cd637264beb87bc38caffbce112",
            "8a454e08f9e24605b511cca3202e9bda",
            "dca5adf80ef548669c2c427de59d813f",
            "311b56bee70b4742b0a4798a844c7ae8",
            "e890a6e6fce14af994570a8d90ef830e",
            "fddd4bef12ed429f932af3a270af37c8",
            "06796b0231564291a0194c16f54b6649",
            "c5e4918837fe4363b2c56c0ffb8d3bfc",
            "4656b891700e4e19be10cbbde829d8a4",
            "59036c1bfadd44ac90993bc44aeeb048",
            "cd1480e1a5a14a37be7534cc095e9357",
            "ff2c73258fc0439da26d91c3fd997a28",
            "765566c819214ff4ae7e9bfd2460a21b",
            "b39a9f7796144a078c32511e42329e45",
            "1411506fa0764e51852898270ca60454",
            "421b7a87bcf74f5384edbe0918161c10",
            "961bb99ee0a84265bb0ce6d43a6a5d2a",
            "86f524ee3cdd4bb59c9c30ac6ef92135",
            "55d7e6b72dc040db8d290cd6bf338912",
            "b5226d91bab64f5d81495118c48c2f33",
            "b4b2de9a20f1416ea2391ffc98b00572",
            "e6906d8bc7b442e5bd133fb5dfcf3a51",
            "dab39c446e844a0d83573f94723e0eeb",
            "56ed682cb9e7475bbec1439ff4b09517",
            "6bbcf32781424f24845117f676b53822",
            "7cbedad663d5496a86c0b7addf5ba6b5",
            "20d304c936d242e6abae011f5d6ae1c6",
            "0e4e1e85049949f395759943b4f880de",
            "70748f7bbe284433af3bf0b86b6bf4f9",
            "e96c11a8c4ae44aa8beec893d2ade0f2",
            "f801a2f340f24e84b7f427956c83bc53"
          ]
        },
        "id": "g-tE5U04auRu",
        "outputId": "1ba81047-f5f0-4ce9-8e1c-223748a561ed"
      },
      "source": [
        "import matplotlib\n",
        "import numpy as np\n",
        "import torch\n",
        "\n",
        "# 导入pytorch内置的mnist数据\n",
        "from torchvision.datasets import mnist\n",
        "\n",
        "# 导入预处理模块\n",
        "import torchvision.transforms as transforms\n",
        "from torch.utils.data import DataLoader\n",
        "\n",
        "# 导入nn及优化器\n",
        "import torch.nn.functional as F\n",
        "import torch.optim as optim\n",
        "from torch import nn\n",
        "\n",
        "\n",
        "# 2.定义一些超参数\n",
        "train_batch_size = 64\n",
        "test_batch_size = 64\n",
        "learning_rate = 0.01\n",
        "num_epoches = 20\n",
        "lr = 0.01\n",
        "momentum = 0.5\n",
        "\n",
        "\n",
        "# 3.下载数据预处理\n",
        "# 定义预处理函数，这些预处理依次放在Compose函数中。\n",
        "# 1）transforms.Compose可以把一些转换函数组会在一起\n",
        "# 2）Normalize([0,0.5],[0,0.5])对张量归一化，两个0.5分别表示对张量进行归一化的全局平均值核方差。\n",
        "# 3）download参数控制是否需要下载，若./data目录下已有MNIST，选择False\n",
        "# 4）用DataLoader得到生成器看，节省内存。\n",
        "transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])\n",
        "#  下载数据，并对数据做预处理\n",
        "train_dataset = mnist.MNIST('./data', train=True, transform=transform, download=True)\n",
        "test_dataset = mnist.MNIST('./data', train=False, transform=transform)\n",
        "# dataloader是一个可迭代对象，可以使用迭代器一样使用。\n",
        "train_loader = DataLoader(train_dataset, batch_size=train_batch_size, shuffle=True)\n",
        "test_loader = DataLoader(test_dataset, batch_size=test_batch_size, shuffle=False)\n",
        "\n",
        "# 3.可视化源数据\n",
        "import matplotlib.pyplot as plt\n",
        "%matplotlib inline\n",
        "\n",
        "examples = enumerate(test_loader)\n",
        "batch_idx, (examples_data, examples_targets) = next(examples)\n",
        "\n",
        "fig = plt.figure()\n",
        "for i in range(6):\n",
        "    plt.subplot(2, 3, i + 1)\n",
        "    plt.tight_layout()\n",
        "    plt.imshow(examples_data[i][0], cmap='gray', interpolation='none')\n",
        "    plt.title('Groud Truth:{}'.format(examples_targets[i]))\n",
        "    plt.xticks([])\n",
        "    plt.yticks([])"
      ],
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz\n",
            "Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ./data/MNIST/raw/train-images-idx3-ubyte.gz\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.jupyter.widget-view+json": {
              "model_id": "1a32beb3196b435e81d9233cf04d95d7",
              "version_minor": 0,
              "version_major": 2
            },
            "text/plain": [
              "  0%|          | 0/9912422 [00:00<?, ?it/s]"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw\n",
            "\n",
            "Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz\n",
            "Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to ./data/MNIST/raw/train-labels-idx1-ubyte.gz\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.jupyter.widget-view+json": {
              "model_id": "6a27f422bcb34d9088444cb8c0ae72e0",
              "version_minor": 0,
              "version_major": 2
            },
            "text/plain": [
              "  0%|          | 0/28881 [00:00<?, ?it/s]"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw\n",
            "\n",
            "Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz\n",
            "Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw/t10k-images-idx3-ubyte.gz\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.jupyter.widget-view+json": {
              "model_id": "59036c1bfadd44ac90993bc44aeeb048",
              "version_minor": 0,
              "version_major": 2
            },
            "text/plain": [
              "  0%|          | 0/1648877 [00:00<?, ?it/s]"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw\n",
            "\n",
            "Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz\n",
            "Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.jupyter.widget-view+json": {
              "model_id": "b4b2de9a20f1416ea2391ffc98b00572",
              "version_minor": 0,
              "version_major": 2
            },
            "text/plain": [
              "  0%|          | 0/4542 [00:00<?, ?it/s]"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw\n",
            "\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)\n",
            "  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZQAAAELCAYAAAD+9XA2AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAb5UlEQVR4nO3de7BU1Zn38d8DIggkqOANLxAxGpFwExJFvCWOCAIiSGRgjJcZ0SBqlQY0QkolOKawSkejgKmKBaKlTgAJIhqsDEKMSgmvaCQQCxwQB1COBMJVbuv9o5vtXtvTTXef1X26+3w/VadqPazdez/nnEU/vfbeZ21zzgkAgLpqVN8JAACqAwUFABAEBQUAEAQFBQAQBAUFABAEBQUAEETVFhQze9PM/qMejvuAmT1X6uMiHMYOCtXQx07RCoqZDTOzJWa208y+SLdHmZkV65g55jXVzHakv/aa2b5Y/Fqe+7rEzD6rYz47El8HzOw3ddlnpWPs5PT6pmb2OzNbZ2bbzWy5mfUtdH/VgrGT8z5Gm9lSM/vKzKbVZV9xRSkoZna3pMclPSLpREknSLpV0gWSjszwmsbFyCXJOXerc66lc66lpP+U9NKh2DkX/Yc0syNKlE/LWD4nStot6felOHY5Yuzk7AhJ6yVdLKmVpPGS/tvM2pfg2GWJsZOXDZImSnom5E6DFxQzayVpgqRRzrmZzrntLuV959wI59xX6e2mmdkUM5tvZjslXWpmZ6enjFvNbIWZDYzt15tKmtkNZvZWLP4XM1tlZtvM7ElJeX8iMbO1ZnaPmX0oaaeZHWFmzszOiG0zzcwmmlkLSa9Jahv7pNE2vdmRZvZs+pPjCjPrkWMKQyR9IenP+eZeDRg7knIcO865nc65B5xza51zB51z8yT9r6Rz8829GjB2JOXxvuOcm+2cmyPpy3zzzaYYM5TzJTWV9Iccth0u6SFJ35K0RNIrkhZIOl7S7ZKeN7OzDrcTM2sjabZSn9LaSFqj1KeSQvyrpCslHe2c259pI+fcTkl9JW2IfdLYkO4eKOlFSUdLmivpyViuk81scobdXi/pWddw18Nh7BQ4dszsBElnSlpRYO6VjrFT+PtOMMUoKG0k1cR/KGb2drr67zazi2Lb/sE59xfn3EFJXSW1lPRr59xe59z/SJqn1A/6cPpJWpH+ZLJP0n9J2lRg/k8459Y753YX+HpJess5N985d0DSDEldDnU450Y550YlX2Bm7ZQ6fTG9DsetdIydwsZOE0nPS5runFtVh2NXMsZOAWMntGIUlC8ltbHYuUDnXC/n3NHpvvgx18fabSWtT/+SD1kn6eQcjtk2vq/0J/z1mTfPqtDXxcUH1S5Jzezw50avU2pA/G+A41cqxk6eY8fMGin15rFX0ugAx69UjJ3C3neCKkZBeUfSV5KuymHb+KmdDZJOTf8HOeQ0Sf+Xbu+U1DzWd2KsvVHSqYcCM7N4nKfk6aZdWY4b8tTUT9WwZycSYycv6Vx/p9TF5yHpT8kNFWOnDAQvKM65rZIelDTZzK4xs2+ZWSMz6yqpRZaXLlHqhzjWzJqY2SWSBih1TlCSlksabGbN0xer/j322lclnWNmg9MV+Q75v4C6WC5puJk1NrMrlDotdcjnklqnLwgWzMx6KfWJqMHe3SUxdgowRdLZkgbU8VRJxWPs5Cd94b+ZpMaSGptZkNlMUW4bds5NknSXpLFKffOfS3pa0j2S3s7wmr1K/SL7SqqRNFnST2PnhB9Talr/uVKf5J+PvbZG0lBJv1ZqevtdSX8J9O3cmc5rq6QRkubEjrtK0guSPkmfq21b+y6+Zqn70acm/vl6SbOdc9sD5VyxGDuZxcdO+prbLUpdA9gUu+NnRKDcKw5jJ7Na3nfGK/UnCvdK+rd0e3xdk7aGe0MRACCkql16BQBQWhQUAEAQFBQAQBAUFABAEBQUAEAQed13bGbcElaGnHP1ujT34TBuylaNc+64+k4iG8ZO2ap17DBDARqudfWdACpWrWOHggIACIKCAgAIgoICAAiCggIACIKCAgAIgoICAAiCggIACIKCAgAIoqTPGwbKwc9//nMvPuqoo7y4c+fOUfuaa67Juq8pU6ZE7XfeecfrmzFjRqEpAhWJGQoAIAgKCgAgCAoKACCIvJ4pz8qf5YnVhg/vpZdeitqHuy5SqDVr1njxZZdd5sWffvppUY5bB8uccz3qO4lsymHslMKZZ57pxatWrfLiO++8M2r/5je/KUlOh1Hr2GGGAgAIgoICAAiC24ZRleKnuKT8TnPFTzf88Y9/9PpOP/10Lx4wYEDU7tChg9c3YsQIL3744YdzzgENS7du3bz44MGDXvzZZ5+VMp2CMUMBAARBQQEABEFBAQAEwTUUVIUePfw7GK+++uqM265YscKLBw4c6MU1NTVRe8eOHV7fkUce6cXvvvtu1O7SpYvX17p16ywZA1/r2rWrF+/cudOLX3755VKmUzBmKACAICgoAIAgyuKUV/yWzptvvtnr27Bhgxfv2bMnaj///PNe36ZNm7x49erVoVJEmTvppJO82MxfPCB+mqtPnz5e38aNG3M+zt133+3FHTt2zLjtq6++mvN+0fB06tQpao8ePdrrq9SVqpmhAACCoKAAAIKgoAAAgiiLayiTJk2K2u3bt8/5dbfccosXb9++3YuTt4eWQnyJhPj3JUlLly4tdToNxiuvvOLFZ5xxhhfHx8aWLVsKPs6wYcO8uEmTJgXvCw3b9773vajdokULry+5dFClYIYCAAiCggIACIKCAgAIoiyuocT/9qRz585e38qVK7347LPPjtrdu3f3+i655BIvPu+886L2+vXrvb5TTz015/z279/vxZs3b47ayb9/iEs+oY9rKKWzbt26IPsZM2aMFyefrBe3ZMmSrDEQN3bs2KidHK+V+l7BDAUAEAQFBQAQRFmc8vrTn/5Ua7s2r7/+esa+Y445xovjK3guW7bM6+vZs2fO+cWXe5Gkjz/+OGonT8kde+yxUXvNmjU5HwPlo3///lF7woQJXl9yteEvvvgiav/iF7/w+nbt2lWE7FCpkn8SEV8hO/6eIn1zteFKwQwFABAEBQUAEAQFBQAQRFlcQwnlH//4hxcvXLgw47aHu1aTzZAhQ6J28rrNX//616hdqcsnNHTxc9vJayZJ8d/xokWLipYTKt/FF1+csS/+pwiVjBkKACAICgoAIAgKCgAgiKq6hlIsxx9/vBdPnjw5ajdq5Nfk+N8t1GWZdJTOnDlzvPjyyy/PuO2zzz7rxePHjy9KTqg+3//+9zP2JR91UamYoQAAgqCgAACC4JRXDm677TYvPu6446J28lblv//97yXJCYVLrhDdq1cvL27atGnUrqmp8fomTpzoxTt27AicHapFfLVzSbrxxhu9+P3334/ab7zxRklyKjZmKACAICgoAIAgKCgAgCC4hlKLCy64wIvvvffejNsOGjTIiz/66KOi5IRwZs2a5cWtW7fOuO1zzz3nxTySALm67LLLvDj+aAvJfxRH8hEZlYoZCgAgCAoKACAICgoAIAiuodSiX79+XtykSRMvji99/84775QkJ9TNwIEDo3b37t2zbvvmm29G7fvvv79YKaHKdenSxYudc148c+bMUqZTEsxQAABBUFAAAEFwyivtqKOOitpXXHGF17d3714vjp8G2bdvX3ETQ0GStwLfd999UTt5CjNp+fLlUZulVZCPE088MWpfeOGFXl9yWaaXX365JDmVEjMUAEAQFBQAQBAUFABAEFxDSRszZkzU7tatm9cXXyJBkt5+++2S5ITC3X333V7cs2fPjNsmn9jIrcIo1A033BC1k096fe2110qcTekxQwEABEFBAQAEQUEBAATRYK+hXHnllV78y1/+Mmr/85//9PomTJhQkpwQzl133ZXztqNHj/Zi/vYEhWrXrl3GvuTjwqsRMxQAQBAUFABAEA3mlFdyKY4nnnjCixs3bhy158+f7/W9++67xUsM9S75JL1Cl9PZtm1b1v3El3xp1apVxv0cffTRXpzP6bsDBw548T333BO1d+3alfN+UJj+/ftn7HvllVdKmEn9YIYCAAiCggIACIKCAgAIoqqvocSviySXT/nOd77jxWvWrIna8VuIUf0+/PDDIPv5/e9/78UbN2704hNOOCFqX3vttUGOeTibNm2K2g899FBJjtmQ9O7d24vjy9c3RMxQAABBUFAAAEFU9SmvDh06RO1zzz0367bxWzPjp79QmZK3fl911VVFP+bQoUMLfu3+/fuj9sGDB7NuO3fu3Ki9dOnSrNv++c9/LjgnHN7VV1/txfHT7O+//77Xt3jx4pLkVJ+YoQAAgqCgAACCoKAAAIKoqmsoyZU+FyxYkHHb+BMaJWnevHlFyQn1Y/DgwV48duzYqB1fAuVwzjnnHC/O53bfZ555xovXrl2bcdtZs2ZF7VWrVuV8DJRW8+bNvbhfv34Zt505c6YXJ5fFqUbMUAAAQVBQAABBUFAAAEFU1TWUkSNHevFpp52WcdtFixZ5sXOuKDmhPEyaNCnIfoYPHx5kP6hMyUcSJJ/CGP8boccff7wkOZUTZigAgCAoKACAICr6lFdypc/bb7+9njIB0BAkT3n16tWrnjIpT8xQAABBUFAAAEFQUAAAQVT0NZQLL7zQi1u2bJlx2+SS9Dt27ChKTgDQUDFDAQAEQUEBAARBQQEABFHR11AO54MPPojaP/7xj72+LVu2lDodAKhqzFAAAEFQUAAAQVg+q+yaGUvyliHnnNV3DtkwbsrWMudcj/pOIhvGTtmqdewwQwEABEFBAQAEQUEBAASR723DNZLWFSMRFKxdfSeQA8ZNeWLsoFC1jp28LsoDAJAJp7wAAEFQUAAAQVBQAABBUFAAAEFQUAAAQVBQAABBUFAAAEFQUAAAQVBQAABBUFAAAEFQUAAAQVBQAABBUFAAAEFUbUExszfN7D/q4bgPmNlzpT4uwmHsoFANfewUraCY2TAzW2JmO83si3R7lJnV6/PPzWyqme1If+01s32x+LU893WJmX1Wx3yONbOX0z+ndWY2vC77qwaMnbzz+q6Z7SmHN5T6xtjJeR+jzWypmX1lZtPqsq+4ohQUM7tb0uOSHpF0oqQTJN0q6QJJR2Z4TeNi5JLknLvVOdfSOddS0n9KeulQ7JzrG8sn34ePFeopSXuV+hmNkDTFzM4p0bHLDmOnIE9Jeq/Exyw7jJ28bJA0UdIzIXcavKCYWStJEySNcs7NdM5tdynvO+dGOOe+Sm83zcymmNl8M9sp6VIzOzs9ZdxqZivMbGBsv95U0sxuMLO3YvG/mNkqM9tmZk9KyvsTiZmtNbN7zOxDSTvN7Agzc2Z2RmybaWY20cxaSHpNUtvYJ4226c2ONLNnzWx7+vvokeF4LSQNkfRL59wO59xbkuZKui7f3KsBY0dSjmMnts9hkrZK+lO+OVcTxo6kPMaOc262c26OpC/zzTebYsxQzpfUVNIfcth2uKSHJH1L0hJJr0haIOl4SbdLet7MzjrcTsysjaTZksZLaiNpjVKfSgrxr5KulHS0c25/po2cczsl9ZW0IfZJY0O6e6CkFyUdrVSBeDKW62Qzm5wOz5S03zn3cWzXH0hqqDMUxk7uY0dm9m2l3kTvKjDfasLYyWPsFEsxCkobSTXxH4qZvZ2u/rvN7KLYtn9wzv3FOXdQUldJLSX92jm31zn3P5LmKfWDPpx+klakP5nsk/RfkjYVmP8Tzrn1zrndBb5ekt5yzs13zh2QNENSl0MdzrlRzrlR6bClpH8mXrtNqYHeEDF2ch87kvQrSb9zzgW5FlPhGDv5jZ2iKMb5ui8ltTGzIw79cp1zvSTJUheS4kVsfazdVtL69C/5kHWSTs7hmG3j+3LOOTNbn2X7bAp9XVx8UO2S1Cz+84jZIenbiX/7tqTtAXKoRIydHMeOmXWVdJmkbgGOWQ0YO7m/7xRNMWYo70j6StJVOWzrYu0Nkk41s3hOp0n6v3R7p6Tmsb4TY+2Nkk49FJiZxeM8uUS8K8txk9vm62NJR5jZd2P/1kXSijrut1IxdnJ3iaT2kj41s02Sfi5piJn9vzrut1IxdspA8ILinNsq6UFJk83sGjP7lpk1Sn+iapHlpUuU+iGONbMmZnaJpAFKnROUpOWSBptZ8/TFqn+PvfZVSeeY2WBL3SVxh/xfQF0slzTczBqb2RWSLo71fS6pdfqCYN7S50NnS5pgZi3M7AKl/kPMqGvSlYixk5ffSuqg1CmbrpKmKvW99KlDvhWLsZOf9IX/ZpIaS2psZs0swB1mRblt2Dk3SakLhWOV+uY/l/S0pHskvZ3hNXuV+kX2lVQjabKknzrnVqU3eUyp22s/lzRd0vOx19ZIGirp10pNfb8r6S+Bvp0703ltVeq23jmx466S9IKkT9LnatvWvouvWep+9Kmxfxol6ShJX6T39TPnXEOdoTB2soiPHefcLufcpkNfSp0+3eOc2xwo94rD2Mmslved8ZJ2S7pX0r+l2+PrmrQ5V7azJwBABanapVcAAKVFQQEABEFBAQAEQUEBAARBQQEABJHXfcdmxi1hZcg5V69Lcx8O46Zs1TjnjqvvJLJh7JStWscOMxSg4VpX3wmgYtU6digoAIAgKCgAgCAoKACAICgoAIAgKCgAgCAoKACAICgoAIAgKCgAgCAoKACAICgoAIAgKCgAgCAoKACAIPJabbjStGjRImo/8sgjXt8tt9zixcuWLYvaQ4cO9frWrWMNPQA4HGYoAIAgKCgAgCCq+pTXSSedFLVvvvlmr+/gwYNefO6550bt/v37e31PPfVUEbJDfenevbsXz54924vbt29f9Bwuv/xyL165cmXUXr9+fdGPj/IyYMAAL547d64Xjx49OmpPnTrV6ztw4EDxEssTMxQAQBAUFABAEBQUAEAQVXUN5bjjjvPi6dOn11MmKGd9+vTx4qZNm5Y8h+Q585tuuilqDxs2rNTpoB60bt06ak+ePDnrtk8++WTUfuaZZ7y+3bt3h02sDpihAACCoKAAAIKo6FNed9xxhxcPGjTIi3/wgx8UtN+LLrrIixs18uvuBx98ELUXL15c0DFQWkcc8fVQ79evXz1mkhJfmUGS7rrrrqgdX+FBknbu3FmSnFBa8feZU045Jeu2L7zwQtTes2dP0XKqK2YoAIAgKCgAgCAoKACAICr6Gspjjz3mxcnlVAo1ePDgrHF89eFrr73W60ueG0d5uPTSS6P2+eef7/VNmjSp1OnomGOO8eKOHTtG7ebNm3t9XEOpDsnb08eNG5fza2fMmBG1nXPBcgqNGQoAIAgKCgAgCAoKACAIy+d8nJnV+8m7+fPnR+2+fft6fXW5hvLll19G7R07dnh97dq1y3k/jRs3LjiHQjnnrOQHzUN9jJtOnTp58Ztvvhm1479ryX90gfTN338xxPORpN69e0ft+GMXJGnz5s3FSmOZc65HsXYeQjm854TSo4f/o37vvfcybrt//34vbtKkSVFyqoNaxw4zFABAEBQUAEAQZX/b8MUXX+zFZ511VtROnuLK55RX8qlnCxYsiNrbtm3z+n70ox95cbbb/X72s59F7SlTpuScD8IaP368F8eXM7niiiu8vlKc4pKkY489Nmonx3WoW95RvoYMGZLztvH3o0rCDAUAEAQFBQAQBAUFABBE2V1Dad++vRe/+OKLXtymTZuc9xVfImXWrFle34MPPujFu3btymk/kjRy5MionXxKZHwZj2bNmnl98aeuSdK+ffsyHhP5ueaaa7w4uUT96tWro/bSpUtLklNS/Npb8ppJ/DbirVu3liollFDysRhxe/fu9eJ8lmUpJ8xQAABBUFAAAEFQUAAAQZTdNZT4o1ql/K6ZLFq0yIuHDRsWtWtqagrOKXkN5eGHH47ajz76qNcXX3o8uSz63LlzvXjNmjUF5wTf0KFDvTi5BPzkyZNLmY6kb14PHDFiRNQ+cOCA1zdx4sSozbW16tCrV6+scVzyEQXLly8vSk7FxgwFABAEBQUAEETZnfLKR/L2z5tuusmL63KaK5v4qav4aQxJ6tmzZ1GOiW9q1apV1D7vvPOyblsfy+DEby+X/NO3K1eu9PoWLlxYkpxQOvm8F1TLMk3MUAAAQVBQAABBUFAAAEGU/TWURo0y17wf/vCHJczka2ZfPyAxmV+2fB944AEvvu6664Lm1dA0bdo0ap988sle3wsvvFDqdL6hQ4cOGfs++uijEmaC+pB8QmNSfIkdrqEAABBDQQEABEFBAQAEUXbXUG699VYvLsdHow4YMCBqd+vWzeuL55vMPXkNBXWzffv2qJ1cqqJz585eHH/87pYtW4qSz/HHH+/FySX14956662i5ID61bt376g9fPjwrNvGHzX+2WefFS2nUmKGAgAIgoICAAii7E55xU8n1ZfkUxg7duzoxffdd19O+9m8ebMXs4psWLt3747ayZWbhwwZ4sWvvvpq1E6uEJ2PTp06efHpp58etZOrCzvnMu6nHE/lou5at24dtbP9CYEkvfHGG8VOp+SYoQAAgqCgAACCoKAAAIIou2so5WDcuHFefNttt+X82rVr10bt66+/3uv79NNP65QXMrv//vu9OL48jiRdeeWVUbsuy7IkH4kQv06Sz9NFp02bVnAOKF/ZbhWPL7UiSU8//XSx0yk5ZigAgCAoKACAICgoAIAguIaSNn/+/Kh91llnFbyfv/3tb1Gb5TVKZ9WqVV78k5/8xIu7du0atc8444yCjzNz5syMfdOnT/fi5OOh4+J/Q4PKdcopp3hxtuVWksurJB9hXg2YoQAAgqCgAACCKLtTXsnbPbMtX9C3b9+s+/rtb38btdu2bZt12/hx6rIsRjksHYNviq9GnFyZOJRPPvkk522TS7jwBMfK1KtXLy/O9n41Z86cYqdT75ihAACCoKAAAIKgoAAAgii7ayhTpkzx4kmTJmXcdt68eV6c7dpHPtdF8tl26tSpOW+L6pa8/peM47hmUh3iy9UnJZfpefzxx4udTr1jhgIACIKCAgAIouxOec2ePduLx4wZ48XJpykWQ/JJiytXrvTikSNHRu2NGzcWPR9UhuQTGrM9sRHVoU+fPhn7kquLb9u2rdjp1DtmKACAICgoAIAgKCgAgCDK7hrKunXrvHjYsGFePGjQoKh95513FiWHhx56yIufeuqpohwH1aVZs2ZZ+1lhuPI1adLEizt06JBx2z179njxvn37ipJTOWGGAgAIgoICAAiCggIACKLsrqEkLV68OGO8YMECry/+9yGSv5T83Llzvb740vaSv0xG/KmLQK5uvPFGL966dasX/+pXvyplOiiC5LJMyacuxh9LsHr16pLkVE6YoQAAgqCgAACCKPtTXtm8/vrrWWOglN577z0vfvTRR7144cKFpUwHRXDgwAEvHjdunBfHl9tZtmxZSXIqJ8xQAABBUFAAAEFQUAAAQVg+S2ybGetxlyHnXOZHA5YBxk3ZWuac61HfSWTD2ClbtY4dZigAgCAoKACAICgoAIAgKCgAgCAoKACAICgoAIAgKCgAgCAoKACAICgoAIAgKCgAgCDyXb6+RtK6YiSCgrWr7wRywLgpT4wdFKrWsZPXWl4AAGTCKS8AQBAUFABAEBQUAEAQFBQAQBAUFABAEBQUAEAQFBQAQBAUFABAEBQUAEAQ/x8Y3WwkQGyQEwAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 432x288 with 6 Axes>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "wFda8i7Fd2pE"
      },
      "source": [
        "# 4.构建模型\n",
        "# 4.1 构建网络\n",
        "class Net(nn.Module):\n",
        "    \"\"\"\n",
        "    使用sequential构建网络，Sequential()函数功能将网络的层组合到一起\n",
        "    \"\"\"\n",
        "    def __init__(self, in_dim, n_hidden_1, n_hidden_2, out_dim):\n",
        "        super(Net, self).__init__()\n",
        "        self.layer1 = nn.Sequential(nn.Linear(in_dim, n_hidden_1), nn.BatchNorm1d(n_hidden_1))\n",
        "        self.layer2 = nn.Sequential(nn.Linear(n_hidden_1, n_hidden_2), nn.BatchNorm1d(n_hidden_2))\n",
        "        self.layer3 = nn.Sequential(nn.Linear(n_hidden_2, out_dim))\n",
        "\n",
        "    def forward(self, x):\n",
        "        x = F.relu(self.layer1(x))\n",
        "        x = F.relu(self.layer2(x))\n",
        "        x = self.layer3(x)\n",
        "        return x\n",
        "\n"
      ],
      "execution_count": 6,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "yWq6D894eE5-"
      },
      "source": [
        "# 4.2 实例化网络\n",
        "# 检测是否有可用GPU，有则使用，否则使用CPU\n",
        "device = torch.device(\"cuda:0\" if torch.cuda.is_available() else \"cpu\")\n",
        "# 实例化网络\n",
        "model = Net(28 * 28, 300, 100, 10)\n",
        "model.to(device)\n",
        "\n",
        "# 定义损失函数和优化器\n",
        "criterion = nn.CrossEntropyLoss()\n",
        "optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum)"
      ],
      "execution_count": 7,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Lh6uJ0rojSvC",
        "outputId": "dd4b7f78-3b55-4935-feea-1a6e5c6eb37f"
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/drive\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "8Q6M0VsyeMXb",
        "outputId": "e721b4e7-dedd-4353-abec-0607285a9e01"
      },
      "source": [
        "# 5.训练模型\n",
        "# 包括对训练数据的训练模型，然后用测试数据的验证模型\n",
        "# 5.1 训练模型\n",
        "losses=[]\n",
        "acces=[]\n",
        "eval_losses=[]\n",
        "eval_acces=[]\n",
        "for epoch in range(num_epoches):\n",
        "  train_loss=0\n",
        "  train_acc=0\n",
        "  model.train()\n",
        "  # 动态修改参数学习率\n",
        "  if epoch%5==0:\n",
        "    optimizer.param_groups[0]['lr']*=0.1\n",
        "  for img,label in train_loader:\n",
        "    img=img.to(device)\n",
        "    label=label.to(device)\n",
        "    img=img.view(img.size(0),-1)\n",
        "    # 前向传播\n",
        "    out=model(img)\n",
        "    loss=criterion(out,label)\n",
        "    # 反向传播\n",
        "    optimizer.zero_grad()\n",
        "    loss.backward()\n",
        "    optimizer.step()\n",
        "    # 记录误差\n",
        "    train_loss+=loss.item()\n",
        "    # 计算分类的准确率\n",
        "    _,pred=out.max(1)\n",
        "    num_corrent=(pred==label).sum().item()\n",
        "    acc=num_corrent/img.shape[0]\n",
        "    train_acc+=acc\n",
        "\n",
        "  losses.append(train_loss/len(train_loader))\n",
        "  acces.append(train_acc/len(train_loader))\n",
        "\n",
        "  # 在测试集上检验效果\n",
        "  eval_loss=0\n",
        "  eval_acc=0\n",
        "  # 将模式改为预测模式\n",
        "  model.eval()\n",
        "  for img,label in test_loader:\n",
        "    img=img.to(device)\n",
        "    label=label.to(device)\n",
        "    img=img.view(img.size(0),-1)\n",
        "    out=model(img)\n",
        "    loss=criterion(out,label)\n",
        "    # 记录误差\n",
        "    eval_loss+=loss.item()\n",
        "    # 计算准确率\n",
        "    _,pred=out.max(1)\n",
        "    num_corrent=(pred==label).sum().item()\n",
        "    acc=num_corrent/img.shape[0]\n",
        "    eval_acc+=acc\n",
        "  eval_losses.append(eval_loss/len(test_loader))\n",
        "  eval_acces.append(eval_acc/len(test_loader))\n",
        "  print('epoch: {},Train Loss: {:.4f},Train Acc: {:.4f},Test Loss:{:.4f},Test Acc:{:.4f}'.format(epoch,train_loss/len(train_loader),train_acc/len(train_loader),eval_loss/len(test_loader),eval_acc/len(test_loader)))\n"
      ],
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "epoch: 0,Train Loss: 1.0339,Train Acc: 0.7828,Test Loss:0.5562,Test Acc:0.9004\n",
            "epoch: 1,Train Loss: 0.4821,Train Acc: 0.8995,Test Loss:0.3499,Test Acc:0.9257\n",
            "epoch: 2,Train Loss: 0.3490,Train Acc: 0.9193,Test Loss:0.2701,Test Acc:0.9389\n",
            "epoch: 3,Train Loss: 0.2827,Train Acc: 0.9319,Test Loss:0.2250,Test Acc:0.9465\n",
            "epoch: 4,Train Loss: 0.2403,Train Acc: 0.9417,Test Loss:0.1965,Test Acc:0.9529\n",
            "epoch: 5,Train Loss: 0.2214,Train Acc: 0.9456,Test Loss:0.1970,Test Acc:0.9526\n",
            "epoch: 6,Train Loss: 0.2178,Train Acc: 0.9472,Test Loss:0.1912,Test Acc:0.9522\n",
            "epoch: 7,Train Loss: 0.2138,Train Acc: 0.9475,Test Loss:0.1896,Test Acc:0.9532\n",
            "epoch: 8,Train Loss: 0.2115,Train Acc: 0.9482,Test Loss:0.1857,Test Acc:0.9553\n",
            "epoch: 9,Train Loss: 0.2073,Train Acc: 0.9495,Test Loss:0.1846,Test Acc:0.9546\n",
            "epoch: 10,Train Loss: 0.2063,Train Acc: 0.9487,Test Loss:0.1843,Test Acc:0.9560\n",
            "epoch: 11,Train Loss: 0.2053,Train Acc: 0.9502,Test Loss:0.1833,Test Acc:0.9547\n",
            "epoch: 12,Train Loss: 0.2058,Train Acc: 0.9503,Test Loss:0.1845,Test Acc:0.9550\n",
            "epoch: 13,Train Loss: 0.2080,Train Acc: 0.9493,Test Loss:0.1823,Test Acc:0.9554\n",
            "epoch: 14,Train Loss: 0.2071,Train Acc: 0.9488,Test Loss:0.1840,Test Acc:0.9548\n",
            "epoch: 15,Train Loss: 0.2057,Train Acc: 0.9496,Test Loss:0.1833,Test Acc:0.9543\n",
            "epoch: 16,Train Loss: 0.2053,Train Acc: 0.9497,Test Loss:0.1827,Test Acc:0.9558\n",
            "epoch: 17,Train Loss: 0.2057,Train Acc: 0.9498,Test Loss:0.1843,Test Acc:0.9551\n",
            "epoch: 18,Train Loss: 0.2067,Train Acc: 0.9495,Test Loss:0.1819,Test Acc:0.9554\n",
            "epoch: 19,Train Loss: 0.2067,Train Acc: 0.9493,Test Loss:0.1824,Test Acc:0.9557\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 299
        },
        "id": "FnEEpua2j3bk",
        "outputId": "302c1fdd-a5a7-4897-ff85-314e9cb04d7b"
      },
      "source": [
        "plt.title('trainloss')\n",
        "plt.plot(np.arange(len(losses)),losses)\n",
        "plt.legend(['Train Loss'],loc='upper right')"
      ],
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<matplotlib.legend.Legend at 0x7efd0aff3310>"
            ]
          },
          "metadata": {},
          "execution_count": 11
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXQAAAEICAYAAABPgw/pAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3de3xU9Z3/8ddnLrlAAokQBBIoasGfioiYYrX1rq3Srnbt1p+XWrzs+rNbxa5tXduurvXXbm+P3X3Y1q5aa7WuLepaLa36szcvVIsK3sELSFGCCIiQcAvJZD6/P+YkjDEhEzLJyZzzfj4e85g553xnzieH4T3fOfM955i7IyIipS8RdgEiIlIcCnQRkYhQoIuIRIQCXUQkIhToIiIRoUAXEYkIBbrEjpndYGZXFdj2VjP75mDXJFIMqbALEOkvM1sF/L27/2FPnu/uFxe3IpHhQT10iRQzUydFYkuBLiXFzG4HJgO/MbOtZnaFmbmZXWhmbwJ/CtrdbWZvm1mzmT1mZgflvUbXbhQzO9bMmszsS2a23szWmtn5u1n/P5jZCjN718wWmNnEYL6Z2X8Gr9FiZi+a2fRg2RwzW2ZmW8xsjZl9eRA3kcSYAl1KirufC7wJ/I27VwF3BYuOAQ4APh5MPwhMBcYBzwB37OZlxwOjgXrgQuB6M6vt3sjMjge+DZwBTADeAOYHiz8GHA1MC17rDGBjsOynwP9x92pgOsGHjkix6eupRMU17r6tc8Ldb+l8bGbXAJvMbLS7N/fw3HbgWnfPAA+Y2VZgf2BRt3bnALe4+zPB6341eN0pwWtUA/8LeMrdX+72+gea2fPuvgnYNKC/VKQX6qFLVKzufGBmSTP7jpm9bmYtwKpg0dhenrsxCPNO24GqHtpNJNcrB8Ddt5Lrhde7+5+AHwHXA+vN7CYzGxU0/TQwB3jDzB41syP6/+eJ9E2BLqWop1OE5s87GzgNOJHc7o8pwXwb4HrfAj7QOWFmI4ExwBoAd/+Bux8GHEhu18tXgvlPu/tp5Hb/3Meu3UQiRaVAl1K0Dth3N8urgZ3kes8jgH8r0np/CZxvZjPNrDx43SfdfZWZfcjMDjezNLANaAWyZlZmZucEu3vagRYgW6R6RN5DgS6l6NvAv5jZZuDvelj+c3K7RtYAy3j/vvA9Eox7vwq4B1gL7AecGSweBfyE3P7xN8h9mHw/WHYusCrY/XMxuX3xIkVnusCFiEg0qIcuIhIRCnQRkYhQoIuIRIQCXUQkIkI7UnTs2LE+ZcqUsFYvIlKSlixZ8o671/W0LLRAnzJlCosXLw5r9SIiJcnM3uhtmXa5iIhEhAJdRCQiFOgiIhGh0+eKSFG0t7fT1NREa2tr2KVEQkVFBQ0NDaTT6YKfo0AXkaJoamqiurqaKVOmYDbQE1vGm7uzceNGmpqa2GeffQp+nna5iEhRtLa2MmbMGIV5EZgZY8aM6fe3HQW6iBSNwrx49mRbllygP73qXb77/15BZ4kUEXmvkgv0F5qa+a9HXmfT9vawSxGRYWTjxo3MnDmTmTNnMn78eOrr67um29radvvcxYsXM2/evH6tb8qUKbzzzjsDKbnoSu5H0YbaSgDWbNrBXiPLQq5GRIaLMWPG8NxzzwFwzTXXUFVVxZe//OWu5ZlMhlSq58hrbGyksbFxSOocTCXXQ6+vCQJ98/aQKxGR4e68887j4osv5vDDD+eKK67gqaee4ogjjuDQQw/lyCOP5NVXXwXgkUce4ZOf/CSQ+zC44IILOPbYY9l33335wQ9+UPD6Vq1axfHHH8+MGTM44YQTePPNNwG4++67mT59OocccghHH300AEuXLmX27NnMnDmTGTNmsHz58gH/vSXbQ2/atCPkSkSkN9/4zVKWvdVS1Nc8cOIo/vVvDur385qamnjiiSdIJpO0tLSwcOFCUqkUf/jDH/ja177GPffc877nvPLKKzz88MNs2bKF/fffn89//vMFjQe/9NJLmTt3LnPnzuWWW25h3rx53HfffVx77bU89NBD1NfXs3nzZgBuuOEGLrvsMs455xza2tro6Ojo99/WXckF+ujKNCPLkqzZrEAXkb595jOfIZlMAtDc3MzcuXNZvnw5ZkZ7e8+/xX3iE5+gvLyc8vJyxo0bx7p162hoaOhzXX/5y1/41a9+BcC5557LFVdcAcBHPvIRzjvvPM444wxOP/10AI444gi+9a1v0dTUxOmnn87UqVMH/Lf2GehmdgvwSWC9u0/vYbkB1wFzgO3Aee7+zIAr670e6msr1UMXGcb2pCc9WEaOHNn1+KqrruK4447j3nvvZdWqVRx77LE9Pqe8vLzrcTKZJJPJDKiGG264gSeffJL777+fww47jCVLlnD22Wdz+OGHc//99zNnzhxuvPFGjj/++AGtp5B96LcCJ+9m+SnA1OB2EfBfA6qoAPU1laxRoItIPzU3N1NfXw/ArbfeWvTXP/LII5k/fz4Ad9xxB0cddRQAr7/+OocffjjXXnstdXV1rF69mpUrV7Lvvvsyb948TjvtNF544YUBr7/PQHf3x4B3d9PkNODnnrMIqDGzCQOubDfqayu1y0VE+u2KK67gq1/9KoceeuiAe90AM2bMoKGhgYaGBi6//HJ++MMf8rOf/YwZM2Zw++23c9111wHwla98hYMPPpjp06dz5JFHcsghh3DXXXcxffp0Zs6cyUsvvcTnPve5AddjhRygY2ZTgN/2ssvlt8B33P3PwfQfgX929/ddvcLMLiLXi2fy5MmHvfFGr+dp360bHn2d7zz4Ci994+NUlZfczwAikfTyyy9zwAEHhF1GpPS0Tc1sibv3OMZySIctuvtN7t7o7o11dT1eQakgXUMXtdtFRKRLMQJ9DTApb7ohmDdo6ms1Fl1EpLtiBPoC4HOW82Gg2d3XFuF1e9VQo7HoIsORzrFUPHuyLQsZtvhL4FhgrJk1Af8KpIMV3gA8QG7I4gpywxbP73cV/TS2qpyyZEK7XESGkYqKCjZu3KhT6BZB5/nQKyoq+vW8PgPd3c/qY7kDX+jXWgcokTAm1lTQpJEuIsNGQ0MDTU1NbNiwIexSIqHzikX9UbJDRBpqR6iHLjKMpNPpfl1dR4qv5E7O1am+RmPRRUTylW6g11ayYctOWtsHfkIbEZEoKN1AD0a6rG3WFcZFRKCUA73rNLoaiy4iAqUc6DpaVETkPUo20MePriBh6IdREZFAyQZ6OplgwmidRldEpFPJBjrkdrvo4CIRkZzSDvRa9dBFRDqVdqDXVPJ2SyuZjmzYpYiIhK60A722ko6s83aLxqKLiJR2oGvooohIl9IO9K4LXSjQRURKO9DVQxcR6VLSgV6RTjK2qlw9dBERSjzQIRi6qEAXESn9QG+oqdS1RUVEiECgd/bQs1ldnFZE4q30A72mkrZMlne27Qy7FBGRUJV8oDfUaqSLiAhEINA1Fl1EJKf0A11j0UVEgAgEenVFmlEVKfXQRST2Sj7QAeprR2jooojEXjQCvUbnRRcRiUSgNwRj0d01Fl1E4isygb51Z4aWHZmwSxERCU0kAr1zpEvT5u0hVyIiEp5oBLoOLhIRiUigd/bQFegiEmORCPS9RpZRkU5oLLqIxFokAt3MNHRRRGIvEoEOuYOL1EMXkTiLTKA36MpFIhJzkQn0+ppK3t3WxvY2jUUXkXiKTKB3nhf9LfXSRSSmIhPonUMXV+uHURGJqegEug4uEpGYKyjQzexkM3vVzFaY2ZU9LJ9sZg+b2bNm9oKZzSl+qbs3rrqCVML0w6iIxFafgW5mSeB64BTgQOAsMzuwW7N/Ae5y90OBM4EfF7vQviQTxkSNRReRGCukhz4bWOHuK929DZgPnNatjQOjgsejgbeKV2Lh6ms0dFFE4quQQK8HVudNNwXz8l0DfNbMmoAHgEt7eiEzu8jMFpvZ4g0bNuxBuX0UWqseuojEV7F+FD0LuNXdG4A5wO1m9r7Xdveb3L3R3Rvr6uqKtOpd6msqWbellbZMtuivLSIy3BUS6GuASXnTDcG8fBcCdwG4+1+ACmBsMQrsj/raStxhbbN66SISP4UE+tPAVDPbx8zKyP3ouaBbmzeBEwDM7ABygV78fSp9aKjR0EURia8+A93dM8AlwEPAy+RGsyw1s2vN7NSg2ZeAfzCz54FfAud5CBf47ByL3qQfRkUkhlKFNHL3B8j92Jk/7+q8x8uAjxS3tP6bMLoSM/XQRSSeInOkKEBZKsHe1RUauigisRSpQAcNXRSR+IpeoNdU0rR5e9hliIgMuegFem0laze30pEd8t9kRURCFb1Ar6kkk3XWb2kNuxQRkSEVvUDXaXRFJKYiF+iTOgNdI11EJGYiF+gTg6NFm9RDF5GYiVygjyhLsdfIMvXQRSR2IhfoEAxdVA9dRGImsoG+ZpPGootIvEQz0GtzVy4K4fxgIiKhiWSgN9RW0tqe5d1tbWGXIiIyZCIZ6PU1GrooIvETzUDXwUUiEkORDPSGmhGAxqKLSLxEMtBHVaaoKk9pl4uIxEokA93MNBZdRGInkoEOu4YuiojERWQDvaFWBxeJSLxENtDrayppac2wpbU97FJERIZEdANdp9EVkZiJbqB3nkb3XQW6iMRDdANdPXQRiZnIBvrYkeWUpRIKdBGJjcgGeiJhwWl0FegiEg+RDXTIDV1sUg9dRGIi0oGuHrqIxEnkA/2drTtpbe8IuxQRkUEX7UDXSBcRiZFoB3qNzosuIvER7UBXD11EYiTSgT5+VAXJhKmHLiKxEOlATyUTjB9VoR66iMRCpAMdgvOiq4cuIjEQ+UBvqKmkSedFF5EYiHyg19dW8nZLK+0d2bBLEREZVNEP9JpKsg5vN7eGXYqIyKCKfqBr6KKIxERBgW5mJ5vZq2a2wsyu7KXNGWa2zMyWmtkvilvmnmuoHQHo4CIRib5UXw3MLAlcD5wENAFPm9kCd1+W12Yq8FXgI+6+yczGDVbB/TVhdAWgHrqIRF8hPfTZwAp3X+nubcB84LRubf4BuN7dNwG4+/rilrnnKtJJ6qrL1UMXkcgrJNDrgdV5003BvHzTgGlm9riZLTKzk3t6ITO7yMwWm9niDRs27FnFe6C+ppKmzRq6KCLRVqwfRVPAVOBY4CzgJ2ZW072Ru9/k7o3u3lhXV1ekVfdNBxeJSBwUEuhrgEl50w3BvHxNwAJ3b3f3vwKvkQv4YaGhppK3NreSzXrYpYiIDJpCAv1pYKqZ7WNmZcCZwIJube4j1zvHzMaS2wWzsoh1DkhDbSVtHVne2boz7FJERAZNn4Hu7hngEuAh4GXgLndfambXmtmpQbOHgI1mtgx4GPiKu28crKL7q3Msuq4vKiJR1uewRQB3fwB4oNu8q/MeO3B5cBt26mt2jUWfNbk25GpERAZH5I8Uhbweun4YFZEIi0WgV5WnGF2ZZo2GLopIhMUi0CE3Fl1DF0UkyuIT6LWVOvxfRCItNoHeEBxclPv9VkQkemIT6PU1lWxr66B5R3vYpYiIDIrYBHqDRrqISMTFJtA7x6Ir0EUkquIT6LpykYhEXGwCvXZEmsp0UkMXRSSyYhPoZhYMXdTBRSISTbEJdAiGLmqXi4hEVKwCXUeLikiUxSvQayvZtL2dbTszYZciIlJ08Qr0Go10EZHoilWgdx5cpN0uIhJFsQr0roOL1EMXkQiKVaCPqy4nnTT10EUkkmIV6ImEMbFGQxdFJJpiFejQOXRRBxeJSPTEMtB1gi4RiaL4BXptJeu37NRYdBGJnNgF+tHT6gD470VvhFyJiEhxxS7QZ02u5Zhpddz42Er10kUkUmIX6AD/dNI03t3Wxm1/WRV2KSIiRRPLQJ85qYbj9q/jpsdWslW9dBGJiFgGOsAXT5zG5u3t3PbEqrBLEREpitgG+iGTajjxgHHc9NhKWlrbwy5HRGTAYhvokOulN+9o59bHV4VdiojIgMU60KfXj+akA/fm5oUrad6hXrqIlLZYBzrAF0+cSktrhp89/tewSxERGZDYB/pBE0fz8YP25qcL/0rzdvXSRaR0xT7QIbcvfcvODD/988qwSxER2WMKdOCACaOYc/B4bnl8FZu3t4VdjojIHlGgBy47YRrb2jLcvFD70kWkNCnQA/uPr2bOwRP42eN/5d1t6qWLSOlRoOf54glT2d7ewU8Wal+6iJQeBXqeqXtX8zczJnLbE6vYuHVn2OWIiPRLQYFuZieb2atmtsLMrtxNu0+bmZtZY/FKHFrzTphKa3sHN6mXLiIlps9AN7MkcD1wCnAgcJaZHdhDu2rgMuDJYhc5lD44ropTD5nIz594g3fUSxeRElJID302sMLdV7p7GzAfOK2Hdv8X+C7QWsT6QjHvhKnszHRw46Ovh12KiEjBCgn0emB13nRTMK+Lmc0CJrn7/bt7ITO7yMwWm9niDRs29LvYobJvXRWfmlnP7YveYP2Wkv98EpGYGPCPomaWAP4D+FJfbd39JndvdPfGurq6ga56UF16wlTaO5wbH9W+dBEpDYUE+hpgUt50QzCvUzUwHXjEzFYBHwYWlPIPowD7jB3J3x5az38veoP1Leqli8jwV0igPw1MNbN9zKwMOBNY0LnQ3Zvdfay7T3H3KcAi4FR3XzwoFQ+hS4//IJms8+NHtC9dRIa/PgPd3TPAJcBDwMvAXe6+1MyuNbNTB7vAMH1gzEg+PaueXzz1Jm83q5cuIsNbQfvQ3f0Bd5/m7vu5+7eCeVe7+4Ie2h4bhd55p0uPn0o26/z4kRVhlyIisls6UrQPk/YawWcaG5j/1Gre2rwj7HJERHqlQC/AF477II566SIyvCnQC9BQO4LPNE7izqdXs0a9dBEZphToBfrCcR8E4Ed/Ui9dRIYnBXqB6msqOfNDk7l78WpWv7s97HJERN5Hgd4P/3jcfiTMuP5h9dJFZPhRoPfDhNGVnDV7EncvaeL3y9aFXY6IyHso0PvpSx/fn+n1o/nHO5bw0NK3wy5HRKSLAr2fRlWkuf3C2UyvH80X7niGB19cG3ZJIiKAAn2PjKpI8/MLZnPIpBou+eWz3P+CQl1EwqdA30PVFWluu2A2sybXMG/+s/zm+bfCLklEYk6BPgBV5SluPX82h32glsvmP8uvn1vT95NERAaJAn2ARpanuPX8DzF7n734pzuf495nm8IuSURiSoFeBCPKUtxy3oc4fJ8xXH7X8/zPEoW6iAw9BXqRdIb6R/Yby1f+53nuWry67yeJiBSRAr2IKsuS3Dy3kY9+cCz/fM8L3Pn0m2GXJCIxokAvsop0kp98rpGjp9bxz/e8yC+eVKiLyNBQoA+CinSSG889jOP2r+Nr977I7YveCLskEYkBBfogqUgnueHcwzjxgHFcdd9L/Pwvq8IuSUQiToE+iMpTSX58zmGcdODeXP3rpfzs8b+GXZKIRJgCfZCVpRJcf/YsPn7Q3nzjN8u4eeHKsEsSkYhSoA+BslSCH509izkHj+eb97/MjY++jruHXZaIRIwCfYikkwmuO/NQPjFjAt9+8BUuvG0xTZt05SMRKR4F+hBKJxP84MxDueqTB7Jo5UZO+o/HuHnhSjId2bBLE5EIUKAPsWTCuPCj+/D7y4/hiP3G8M37X+ZTP36cl9Y0h12aiJQ4BXpI6msq+encRq4/exbrWnZy6o/+zDd/u4xtOzNhlyYiJUqBHiIz4xMzJvCHy4/hzNmTufnPf+Vj//kYD7+yPuzSRKQEKdCHgdGVaf7tbw/m7ouPoLIsyfm3Ps0lv3iG9Vtawy5NREqIAn0Y+dCUvbh/3ke5/KRp/G7pOk7890eZ/9SbZLMa4igifVOgDzPlqSTzTpjKg188igMmjOLKX73ImTctYsX6LWGXJiLDnAJ9mNqvror5F32Y7316Bq+u28Ip1y3kP3//GjszHWGXJiLDlAJ9GDMzzvjQJP74pWOYc/AErvvjck65biFPrHhHR5qKyPtYWMHQ2NjoixcvDmXdperR1zbw9XtfpGnTDvYeVc4x0+o4Zto4PvrBsYwekQ67PBEZAma2xN0be1ymQC8t29sy/PaFtTz62gYWvraBltYMCYOZk2o4Zto4jtm/joPrR5NMWNilisggUKBHVKYjy/NNzTz62gYefW0DLzRtxh1qR6Q5amodx0yr46hpYxlXXRF2qSJSJAr0mHh3WxsLl+fC/bHXNvDO1jYADpo4Ktg9U8esD9SSTuqnE5FSpUCPoWzWWba2pav3vuSNTXRknaryFI1TahkzspzqihQjy5NUlaepqkhRXZ5iZHmKqvIU1RW5+5HB4/JUAjPtxhEJmwJdaGlt54kVG3n0tQ08++YmtrRm2Lozd+so4MClVMKoqkgxsiwX8NUVKUZVpIPHaUZVBvdd81KMqkwzqmLX/Iq0PhREBmp3gZ4a6mIkHKMq0pw8fTwnTx//nvnuTmt7tivct7Zm2LKznW07O9i6sz2YzrCta1lw35rh7ZZWlq/P0NLazpbWvj8YUgnr+gCoSCeoSCepSCUpTycoTyW75pWngmXpRNfy/LYV6WTXB8foytyHRVVFSj8ES+wVFOhmdjJwHZAEbnb373Rbfjnw90AG2ABc4O661H0JMDMqy5JUliWpqy7f49dxd3a0d9CyI8OW1nZaWttpCYK/ZUcu8HPBn3u8sz1La6aD1vYOtrRmeCfTxs723PTOTJbW9g5aM9mCvj10qi7P/2aQ/63hvfOqytOkkkYqYSQTRiqRyN0nc9NJs67pXJtEXlsjkejhucH8oeLu7Mxkg1sHO9tz963tefMy2a75XffBc8zo+js7bwl779+fDP6m3DQkLLdNEmakkwnSyQSppFEW3KeTCdKJBOlUbru8Z37Shu23M3enI+t0BPeZrJMN7jvybvnTA7X3qHJqRpQVofr36jPQzSwJXA+cBDQBT5vZAndfltfsWaDR3beb2eeB7wH/u+jVyrBlZowoSzGiLMX40cUbVZPpyNIaBHxn0O9o6+j6gMj/sGjZsWteS2s7a5tbeXXdlq75g7130Yweg77rPpmbnzBwh6w72eB+13Runucty2b9Pe073GnLlN5FUVLBh2Q6kSCRMMxyHxK5z8HcfcJ2zQdIBB8kxq5lZobnbTOnczvltlvXdLAde9rWXUHtxQno/vrmp6bz2Q9/oOivW0gPfTawwt1XApjZfOA0oCvQ3f3hvPaLgM8Ws0iJr1QyQVUyQVX5wPYOZrPOtrZM8K2hnUxHt15ZR2cvLNtjLy13nyWT1/b9z892a5/3eh158927giw/wHZN73qcCAKsa3kQhOWpXbumylOJ3C3dw7yuXVq75neOcuqsP5v393b+PdksZLJZsu50ZHNts573d3Xk/ta2jiyZDqe9Ixvccss6H7d3tstkyWR3zfP3fZAB5NabH9LkLe+c5+5d2yQX9Lu2W25b9jzd9SGR900jlXjvt5RUt8e7vo0lSCbI3QevOxAHTRw1sBfoRSH/S+qB1XnTTcDhu2l/IfBgTwvM7CLgIoDJkycXWKLIwCUSRnVFmuqKNFAZdjkig6KoA5LN7LNAI/D9npa7+03u3ujujXV1dcVctYhI7BXSQ18DTMqbbgjmvYeZnQh8HTjG3XcWpzwRESlUIT30p4GpZraPmZUBZwIL8huY2aHAjcCp7q7rp4mIhKDPQHf3DHAJ8BDwMnCXuy81s2vN7NSg2feBKuBuM3vOzBb08nIiIjJICho64O4PAA90m3d13uMTi1yXiIj0k87SJCISEQp0EZGIUKCLiEREaGdbNLMNwJ6e72Us8E4Ryyk21Tcwqm/ghnuNqm/PfcDdezyQJ7RAHwgzW9zb6SOHA9U3MKpv4IZ7japvcGiXi4hIRCjQRUQiolQD/aawC+iD6hsY1Tdww71G1TcISnIfuoiIvF+p9tBFRKQbBbqISEQM60A3s5PN7FUzW2FmV/awvNzM7gyWP2lmU4awtklm9rCZLTOzpWZ2WQ9tjjWz5uCEZc+Z2dU9vdYg1rjKzF4M1r24h+VmZj8Itt8LZjZrCGvbP2+7PGdmLWb2xW5thnz7mdktZrbezF7Km7eXmf3ezJYH97W9PHdu0Ga5mc0dotq+b2avBP9+95pZTS/P3e17YZBrvMbM1uT9O87p5bm7/f8+iPXdmVfbKjN7rpfnDsk2HBAPLuk03G7kLkj9OrAvUAY8DxzYrc0/AjcEj88E7hzC+iYAs4LH1cBrPdR3LPDbELfhKmDsbpbPIXd1KQM+DDwZ4r/12+QOmAh1+wFHA7OAl/LmfQ+4Mnh8JfDdHp63F7AyuK8NHtcOQW0fA1LB4+/2VFsh74VBrvEa4MsFvAd2+/99sOrrtvzfgavD3IYDuQ3nHnrXtUzdvQ3ovJZpvtOA24LH/wOcYEN0aXF3X+vuzwSPt5A7tXD9UKy7iE4Dfu45i4AaM5sQQh0nAK+7+54eOVw07v4Y8G632fnvs9uAT/Xw1I8Dv3f3d919E/B74OTBrs3df+e5U1xD7nq+DcVcZ3/1sv0KUcj/9wHbXX1BdpwB/LLY6x0qwznQe7qWaffA7GoTvKmbgTFDUl2eYFfPocCTPSw+wsyeN7MHzeygIS0sd13d35nZkuB6rt0Vso2Hwpn0/p8ozO3XaW93Xxs8fhvYu4c2w2FbXkAv1/Ol7/fCYLsk2C10Sy+7rIbD9jsKWOfuy3tZHvY27NNwDvSSYGZVwD3AF929pdviZ8jtRjgE+CFw3xCX91F3nwWcAnzBzI4e4vX3KbgK1qnA3T0sDnv7vY/nvnsPu7G+ZvZ1IAPc0UuTMN8L/wXsB8wE1pLbrTEcncXue+fD/v/TcA70Qq5l2tXGzFLAaGDjkFSXW2eaXJjf4e6/6r7c3VvcfWvw+AEgbWZjh6o+d18T3K8H7iX3tTZfQdeLHWSnAM+4+7ruC8LefnnWde6KCu57usxiaNvSzM4DPgmcE3zgvE8B74VB4+7r3L3D3bPAT3pZd6jvxSA/Tgfu7K1NmNuwUMM50Pu8lmkw3Tma4O+AP/X2hi62YH/bT4GX3f0/emkzvnOfvpnNJre9h+QDx8xGmll152NyP5691K3ZAuBzwWiXDwPNebsWhkqvvaIwt183+e+zucCve2jzEPAxM6sNdil8LJg3qFpBXqUAAAEZSURBVMzsZOAKctfz3d5Lm0LeC4NZY/7vMn/by7oL+f8+mE4EXnH3pp4Whr0NCxb2r7K7u5EbhfEauV+/vx7Mu5bcmxeggtxX9RXAU8C+Q1jbR8l99X4BeC64zQEuBi4O2lwCLCX3i/0i4MghrG/fYL3PBzV0br/8+gy4Pti+LwKNQ/zvO5JcQI/Omxfq9iP34bIWaCe3H/dCcr/L/BFYDvwB2Cto2wjcnPfcC4L34grg/CGqbQW5fc+d78HOUV8TgQd2914Ywu13e/D+eoFcSE/oXmMw/b7/70NRXzD/1s73XV7bULbhQG469F9EJCKG8y4XERHpBwW6iEhEKNBFRCJCgS4iEhEKdBGRiFCgi4hEhAJdRCQi/j/16sjQ1snssQAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    }
  ]
}